# Generated by Django 4.2.30 on 2026-07-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('category_type', models.CharField(choices=[('E', 'Expense'), ('I', 'Income')], default='E', max_length=1)),
            ],
        ),
    ]
