# Generated by Django 4.2.30 on 2026-07-23 12:49


from django.db import migrations
from django.utils import timezone

def create_categories(apps, schema_editor):
    Category = apps.get_model("tracker", "Category")

    expense_categories = [
        "Rent & bills",
        "Groceries",
        "Supplies & home",
        "Dining Out",
        "Drinking Out",
        "Electronics & digital",
        "Health & medicine",
        "Fashion",
        "Vacation",
        "Transport",
        "Subscriptions",
        "Gifts & dates",
        "Entertainment",
        "Others",
    ]

    income_categories = [
        "Salary",
        "Gifts",
        "Others",
    ]

    for name in expense_categories:
        Category.objects.get_or_create(
            name=name,
            category_type="E",
            defaults={"pub_date": timezone.now()},
        )

    for name in income_categories:
        Category.objects.get_or_create(
            name=name,
            category_type="I",
            defaults={"pub_date": timezone.now()},
        )


def remove_categories(apps, schema_editor):
    Category = apps.get_model("tracker", "Category")
    Category.objects.filter(name__in=[
        "Rent & bills", "Groceries", "Supplies & home", "Dining Out",
        "Drinking Out", "Electronics & digital", "Health & medicine",
        "Fashion", "Vacation", "Transport", "Subscriptions",
        "Gifts & dates", "Entertainment", "Salary", "Gifts", "Others",
    ]).delete()
    
class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_entry'),
    ]

    operations = [
        migrations.RunPython(create_categories, remove_categories),
    ]
