# Generated by Django 4.2.30 on 2026-07-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
