# Generated by Django 4.2.30 on 2026-08-09 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_entry_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date entry was created'),
            preserve_default=False,
        ),
    ]
