# Generated by Django 4.2.30 on 2026-08-09 11:12

from django.db import migrations, models
import django.utils.timezone
from django.db.models import F

def backfill_created_date(apps, schema_editor):
    Entry = apps.get_model('tracker', 'Entry')
    Entry.objects.filter(created_date__isnull=True).update(created_date=F('added_date'))

def reverse_backfill(apps, schema_editor):
    pass  # no-op, added_date is untouched

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_entry_notes'),
        ('tracker', '0005_entry_created_date'),
    ]

    operations = [
        migrations.RunPython(backfill_created_date, reverse_backfill),
    ]
